# Form implementation generated from reading ui file 'Widget_velocidad_botones.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Widget_principal(object):
    def setupUi(self, Widget_principal):
        Widget_principal.setObjectName("Widget_principal")
        Widget_principal.resize(1053, 687)
        self.layout_principal_widget = QtWidgets.QVBoxLayout(Widget_principal)
        self.layout_principal_widget.setContentsMargins(0, 0, 0, 0)
        self.layout_principal_widget.setSpacing(0)
        self.layout_principal_widget.setObjectName("layout_principal_widget")
        self.label_Widget_velocidad = QtWidgets.QLabel(parent=Widget_principal)
        self.label_Widget_velocidad.setStyleSheet("#label_Widget_velocidad {\n"
"    color: #e0f7fa;                /* Azul claro */\n"
"    background-color: #102027;     /* Azul muy oscuro */\n"
"    border: 2px solid #4dd0e1;     /* Cian brillante */\n"
"    border-radius: 10px;\n"
"    padding: 10px 15px;\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    font-family: \'Segoe UI\', \'Ubuntu\', sans-serif;\n"
"    letter-spacing: 1px;\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}")
        self.label_Widget_velocidad.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_Widget_velocidad.setObjectName("label_Widget_velocidad")
        self.layout_principal_widget.addWidget(self.label_Widget_velocidad)
        self.frame_contenedor_general = QtWidgets.QFrame(parent=Widget_principal)
        self.frame_contenedor_general.setStyleSheet("QFrame {\n"
"    background-color: #0b181c;        /* Azul muy oscuro, base profunda */\n"
"    border: 2px solid #4dd0e1;        /* Borde cian brillante */\n"
"    border-radius: 12px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"/* Opcional: si el frame contiene otros frames o etiquetas internas */\n"
"QFrame > QLabel {\n"
"    color: #b3e5fc;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #14424b, stop:1 #0b181c\n"
"    );                                      /* Degradado frío */\n"
"    color: #e0f7fa;\n"
"    border: 2px solid #4dd0e1;\n"
"    border-radius: 10px;\n"
"    padding: 8px 14px;\n"
"    font-size: 14px;\n"
"    font-family: \'Segoe UI\', \'Ubuntu\', sans-serif;\n"
"    font-weight: 500;\n"
"    letter-spacing: 0.5px;\n"
"    transition: all 150ms ease-in-out;\n"
"    box-shadow: 0 0 6px rgba(77, 208, 225, 0.3);   /* Sutil resplandor */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #1f5966, stop:1 #14424b\n"
"    );\n"
"    border: 2px solid #80deea;\n"
"    color: #ffffff;\n"
"    box-shadow: 0 0 10px rgba(128, 222, 234, 0.5); /* Más brillo */\n"
"    transform: scale(1.02);                       /* Ligero agrandamiento */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0a2a33;\n"
"    border: 2px solid #00bcd4;\n"
"    color: #b2ebf2;\n"
"    box-shadow: 0 0 12px rgba(0, 188, 212, 0.6);\n"
"    transform: scale(0.98);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #1c313a;\n"
"    color: #607d8b;\n"
"    border: 1px solid #455a64;\n"
"    box-shadow: none;\n"
"}")
        self.frame_contenedor_general.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_contenedor_general.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_contenedor_general.setObjectName("frame_contenedor_general")
        self.layout_contenedor_general = QtWidgets.QVBoxLayout(self.frame_contenedor_general)
        self.layout_contenedor_general.setContentsMargins(0, 0, 0, 0)
        self.layout_contenedor_general.setSpacing(0)
        self.layout_contenedor_general.setObjectName("layout_contenedor_general")
        self.layout_contenedor_general_botones = QtWidgets.QHBoxLayout()
        self.layout_contenedor_general_botones.setSpacing(0)
        self.layout_contenedor_general_botones.setObjectName("layout_contenedor_general_botones")
        self.button_giro_antihorario = QtWidgets.QPushButton(parent=self.frame_contenedor_general)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_giro_antihorario.sizePolicy().hasHeightForWidth())
        self.button_giro_antihorario.setSizePolicy(sizePolicy)
        self.button_giro_antihorario.setStyleSheet("")
        self.button_giro_antihorario.setText("")
        self.button_giro_antihorario.setObjectName("button_giro_antihorario")
        self.layout_contenedor_general_botones.addWidget(self.button_giro_antihorario)
        self.layout_botones_lineal = QtWidgets.QVBoxLayout()
        self.layout_botones_lineal.setSpacing(0)
        self.layout_botones_lineal.setObjectName("layout_botones_lineal")
        self.button_avanzar = QtWidgets.QPushButton(parent=self.frame_contenedor_general)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_avanzar.sizePolicy().hasHeightForWidth())
        self.button_avanzar.setSizePolicy(sizePolicy)
        self.button_avanzar.setStyleSheet("")
        self.button_avanzar.setText("")
        self.button_avanzar.setObjectName("button_avanzar")
        self.layout_botones_lineal.addWidget(self.button_avanzar)
        self.button_retroceder = QtWidgets.QPushButton(parent=self.frame_contenedor_general)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_retroceder.sizePolicy().hasHeightForWidth())
        self.button_retroceder.setSizePolicy(sizePolicy)
        self.button_retroceder.setStyleSheet("")
        self.button_retroceder.setText("")
        self.button_retroceder.setObjectName("button_retroceder")
        self.layout_botones_lineal.addWidget(self.button_retroceder)
        self.layout_botones_lineal.setStretch(0, 10)
        self.layout_botones_lineal.setStretch(1, 10)
        self.layout_contenedor_general_botones.addLayout(self.layout_botones_lineal)
        self.button_giro_horario = QtWidgets.QPushButton(parent=self.frame_contenedor_general)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_giro_horario.sizePolicy().hasHeightForWidth())
        self.button_giro_horario.setSizePolicy(sizePolicy)
        self.button_giro_horario.setStyleSheet("")
        self.button_giro_horario.setText("")
        self.button_giro_horario.setObjectName("button_giro_horario")
        self.layout_contenedor_general_botones.addWidget(self.button_giro_horario)
        self.slider_velocidad = QtWidgets.QSlider(parent=self.frame_contenedor_general)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_velocidad.sizePolicy().hasHeightForWidth())
        self.slider_velocidad.setSizePolicy(sizePolicy)
        self.slider_velocidad.setStyleSheet("")
        self.slider_velocidad.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.slider_velocidad.setObjectName("slider_velocidad")
        self.layout_contenedor_general_botones.addWidget(self.slider_velocidad)
        self.layout_contenedor_general_botones.setStretch(0, 15)
        self.layout_contenedor_general_botones.setStretch(1, 25)
        self.layout_contenedor_general_botones.setStretch(2, 15)
        self.layout_contenedor_general_botones.setStretch(3, 5)
        self.layout_contenedor_general.addLayout(self.layout_contenedor_general_botones)
        self.layout_principal_widget.addWidget(self.frame_contenedor_general)
        self.layout_principal_widget.setStretch(0, 1)
        self.layout_principal_widget.setStretch(1, 8)

        self.retranslateUi(Widget_principal)
        QtCore.QMetaObject.connectSlotsByName(Widget_principal)

    def retranslateUi(self, Widget_principal):
        _translate = QtCore.QCoreApplication.translate
        Widget_principal.setWindowTitle(_translate("Widget_principal", "Form"))
        self.label_Widget_velocidad.setText(_translate("Widget_principal", "Velocidades "))
